apiVersion: v1
kind: ReplicationController
metadata:
  name: ecs
  labels:
    name: ecs
spec:
  replicas: 3
  selector:
    name: ecs
  template:
    metadata:
      labels:
        name: ecs
    spec:
      containers:
        - name: ecs
          image: arvindkandhare/ecs-reduced-footprint:2.1
          volumeMounts:
            - mountPath: "/host"
              name: host
            - mountPath: "/data"
              name: data
            - mountPath: "/opt/storageos/logs"
              name: log
            - mountPath: "/vagrant"
              name: vagrant
            - mountPath: "/dae"
              name: dae
            - mountPath: "/var/run/dbus"
              name: dbus

          ports:
          - containerPort: 4443

      volumes:
          - name: host 
            hostPath:
               path: "/host"

          - name: log 
            hostPath:
               path: "/var/log/vipr/emcvipr-object"
  
          - name: data 
            hostPath:
                path: "/data"


          - name: vagrant 
            hostPath:
                path: "/vagrant"
    
          - name: dae
            hostPath:
                path: "/ecs"

          - name: dbus
            hostPath:
                path: "/var/run/dbus"
