apiVersion: v1
kind: ReplicationController
metadata:
  name: ecs
  labels:
    name: ecs
spec:
  replicas: 3
  selector:
    name: ecs
  template:
    metadata:
      labels:
        name: ecs
    spec:
      containers:
        - name: ecs
          image: emccorp/ecs-software
          volumeMounts:
            - mountPath: "/host"
              name: host
            - mountPath: "/data"
              name: data
            - mountPath: "/opt/storageos/logs"
              name: log

          ports:
            - containerPort: 6379

      volumes:
          - name: host 
            hostPath:
               path: "/host"

          - name: log 
            hostPath:
               path: "/var/log/vipr/emcvipr-object"
  
          - name: data 
            hostPath:
                path: "/data"
    
