#!/bin/bash

# Copyright 2015 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Ugly hack to do nothing and wait for SIGTERM


## Export the bucket via NFS

set -v
mkdir -p /share/$AWS_BUCKET
chmod 777 /share

function start()
{
    cat /etc/sysconfig/nfs
    # prepare /etc/exports
    for i in "$@"; do
        echo "$i *(rw,sync,no_root_squash,insecure,no_subtree_check)" >> /etc/exports
        echo "Serving $i"
    done

    sudo mount -t nfsd nfsd /proc/fs/nfsd
    
    service rpcbind restart
    service nfs-kernel-server restart

    echo "NFS started"
}

function stop()
{
    echo "Stopping NFS"

    # from /lib/systemd/system/nfs-server.service
    /usr/sbin/rpc.nfsd 0
    /usr/sbin/exportfs -au
    /usr/sbin/exportfs -f

    # from /lib/systemd/system/nfs-mountd.service
    kill $( pidof rpc.mountd )
    # from /lib/systemd/system/proc-fs-nfsd.mount
    umount /proc/fs/nfsd

    echo > /etc/exports
    exit 0
}


#start /share


/usr/local/bin/wrapdocker
s3fs -d $AWS_BUCKET /share/$AWS_BUCKET/ -o url=$BUCKET_ENDPOINT -o passwd_file=/data/passwd_file -o f2 -o curldbg

echo "root:12345" | chpasswd

if [ ! -d /share/$AWS_BUCKET/project.git ]; then
  mkdir /share/$AWS_BUCKET/project.git

  #chown git:git /$AWS_BUCKET/project.git

  #su git -c "cd /share/$AWS_BUCKET/project.git;git init --bare"
  cd /share/$AWS_BUCKET/project.git
  git init --bare

fi

/usr/sbin/sshd


while true; do
    read
done
