#!/bin/bash

# Copyright 2015 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Ugly hack to do nothing and wait for SIGTERM

mkdir /$AWS_BUCKET

s3fs -d $AWS_BUCKET /$AWS_BUCKET/ -o url=$BUCKET_ENDPOINT -o passwd_file=/data/passwd_file -o f2 -o curldbg
/usr/local/bin/wrapdocker

echo "root:12345" | chpasswd

if [ ! -d /$AWS_BUCKET/project.git ]; then
  mkdir /$AWS_BUCKET/project.git

  #chown git:git /$AWS_BUCKET/project.git

  #su git -c "cd /$AWS_BUCKET/project.git;git init --bare"
  cd /$AWS_BUCKET/project.git
  git init --bare

fi

/usr/sbin/sshd

while true; do
    read
done
